#!/bin/zsh

echo "This will undo any uncommited changes to tracked files."
read -q "REPLY?Do you want to continue? (y/n): "
echo  # move to a new line
if [[ ! "$REPLY" =~ ^[Yy]$ ]] ; then
   echo "Aborting..."
   exit
fi
echo "Dropping changes..."
# Discard all staged and unstaged changes to tracked files across the entire repository.
git restore --source=HEAD --staged --worktree -- :/
